name: causal_complexity_measures
channels:
  - defaults
  - pytorch
dependencies:
  - python=3.7.3
  - pip=19.3.1
  - numpy=1.17.2
  - pytorch=1.3.0
  - torchvision=0.4.1
  - pip:
    - tensorboard==2.0.1
