name: rgm
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - pip=20.0
  - numpy=1.18
  - pandas=1.0
  - seaborn=0.10
  - pytorch=1.5.0
  - torchvision=0.6.0
  - pip:
    - tqdm==4.46
    - wandb==0.9
    - simple-parsing==0.0.10
