name: ccm
channels:
  - defaults
  - pytorch
  - conda-forge
dependencies:
  - python=3.7.3
  - pip=19.3.1
  - numpy=1.17.2
  - pandas=0.25.1
  - seaborn=0.9.0
  - pytorch=1.4.0
  - torchvision=0.5.0
  - fire=0.2.1
  - pip:
    - tensorboard==2.0.1
    - comet_ml==3.0.1
